source "https://rubygems.org"

gem "minima", "~> 2.5"

gem "github-pages", "~> 217", group: :jekyll_plugins

# plugins go here
group :jekyll_plugins do
  gem "webrick"
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
